name: Java CI/CD Pipeline

# Gatilhos: Quando essa esteira deve rodar?
on:
  push:
    branches: [ "main" ] # Roda deploy completo no push da main
  pull_request:
    branches: [ "main" ] # Roda apenas testes nos Pull Requests

jobs:
  # JOB 1: Integra칞칚o Cont칤nua (Build e Testes)
  unit-tests:
    name: 游빍 Run Unit Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do c칩digo
        uses: actions/checkout@v4

      - name: Configurar Java 25
        uses: actions/setup-java@v4
        with:
          java-version: '25' # Tenta usar a vers칚o 25
          distribution: 'temurin' # Distribui칞칚o Eclipse Temurin
          cache: 'maven' # Cacheia depend칡ncias para ser mais r치pido

      - name: Rodar Testes com Maven
        run: mvn test
        # Se os testes falharem, a esteira para aqui.

  # JOB 2: Entrega Cont칤nua (Docker Build & Push)
  build-and-deploy:
    name: 游냡 Docker Build & Push
    needs: unit-tests # S칩 roda se 'unit-tests' passar
    # N칚o roda docker build em Pull Requests, apenas na branch main
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do c칩digo
        uses: actions/checkout@v4

      # Configura o QEMU (necess치rio para builds multiplataforma, opcional mas recomendado)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Configura o Docker Buildx (sistema avan칞ado de build do Docker)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Faz login no Docker Hub usando os Secrets configurados
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Compila a imagem e envia para o Hub
      - name: Build e Push da Imagem
        uses: docker/build-push-action@v6
        with:
          context: . # Pasta onde est치 o Dockerfile
          push: true
          # Tags: Gera uma tag 'latest' e uma com o hash do commit (para versionamento)
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/todo-java-api:latest
            ${{ secrets.DOCKER_USERNAME }}/todo-java-api:${{ github.sha }}